# Information 知识付费平台 - 生产环境配置 (本地测试用)
spring:
  # 数据源配置 - 本地MySQL
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/platform_prod?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin123456

  # Redis配置 - 本地Redis
  redis:
    host: localhost
    port: 6379
    password: redis123456
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

  # 缓存配置
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=30m
  
  # Thymeleaf模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html

# MyBatis Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT配置
jwt:
  secret: InformationPlatformSecretKey2024ForProductionEnvironment
  expiration: 86400000  # 24小时
  header: Authorization
  prefix: Bearer

# 文件上传配置
file:
  upload:
    path: /tmp/uploads/
    max-size: 100MB
    allowed-types: jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx,ppt,pptx,txt,md

# 支付配置
alipay:
  app-id: 2021005181654127
  app-private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCA9PyDQgZRftWPbIA2H0baLyrdZrxEMEGMv8akbvTW3kOQdmP9pP6wrw/8+4sD4cUz76qDB7mkpxn33CkFGaj7Xa+HOnICbwjqauLdEd1/wiwwNWeT3R6awOpjDsHo9QNRM628I0Zfj10OYy+h+yzVWefxyeOcw2yDAaYRr9hyBxuW3URDQ5AGe6X0IKZlQUDp7gXOpz/pTGCU+eGCbvSC+7OZnDtsEEcxmwjz4rhvtu15L82PCaCxKiUWd53hp0iiPkbrDMfU8BmcNvQOV7UvKyEZaPSDkhnH4p0AcmKN42SVgRx+kM6rfNEJgyJypeoAtiN+4YSEkvJXH4NmVzh9AgMBAAECggEAVzldsspty6GmgaQ59GGjYuCUdbyPiu+45qKwkXgbU1pzCLuLVnzLaGaAwfTCSpXi9QYepxIKlzwPbH8Vn8WDbsInf6gghVTlCunRGQaEc226xcDZlkHx+WqTHv1UW2WeIMZ7tM2HRAuMPbcI+N8TrBtrrzeHJPlp5BKxaTUvibAfFES0iW0mW+Z9ux58Wz7w5aeu5WMm9ekxWSnXKooLJsm9ZNGznOQRn1wM4+AvCKgYOneug8r+c6ROfGZ1qwFSPvRAC+GjHOxm+vczwxecP/lCFdYZJTVEl7J8DZQXMeqrbiKkDhQAMLyr0nO7jqWEG/czz/HxnR0NtLNXlW2jAQKBgQC9D8fBfaq2zF7VEQ5Mydp0/CiAvTp1B2yw1osA2pf4LMWrDtYGVIVpGjgqHPvhcFeqJ7Xdyyn0OXuWNeEzADY/Bduyd+LkiOJurzZcyJ38WQRsjf6Xz6Z8hHcQT4ga/L0KGeh7tRL6k45Tk9g+Pxe3Ycf0SJwAKuwnkm6KpAkuJQKBgQCunWxpDHWw11pYqZ6Sv2tYuRlZMalWQ8XdSNVB1lt1GfuccKEypsR9JEossEtnGACXhymWWJYP/hCVnlpYHVLuKnZEbctpnKF9DULZvg9KR6KmmNviTBHP6s/UlFyxJdw3UbP3aO5WibJbLvuGE3xZJNkeNwYS7pyE5vdnUEv1eQKBgDc5T8jl8yKYCa9E3x9w6p23NgF8xIGAnK/+yvWB5Ff6g/aWS8/nilyL6xHqC2zrSsAJ/2Z8vJF45O+YZ2JlUnMQO/8iY6ULktBv33o0o2kde1xWEaK4ZdIDQ2ABSylO38z+iljwKE4HIdCp48Uy2rOXHTfuqZqm7voUHLPkfEX9AoGARf44XItwCajpQC0NsUkloHTh4kzz0e5su9zcDv37vx7hKr5C/2i1zmvjh7JLJ1IJurOlSezMijCPOUo2cKegfHNs4NUZ+oWcfeH48AstWdsJKbqQOU/AvBUlpdKqrR+9/Da16vCWyP19DuvwSrg42grZNTFdL+2Rs/xZI4KeUBECgYAinTcSUxa6vO7m5qUD9xZm+utn/vB6GC3JCahcm38Vr3pzqlUImBTazDXD4agvh5xJqrmmzgDgZLmFYCoYdlCimDx9vAntISc5127o3w/VanlTli4RnnH7G2I9mylVeCC8g0JOp/Iigj0nZjS79+TbI/TGB03nQhQwlhr6Oh1xug==
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlCTj5jttp0gZAu+JyDGqGzUW9Ko4SNU80YLlStHJLY9WJ/kZhLZdKof6M0otKJbzByCCJJ3gFAr0X/Ej2Za17ZjAAwoivKPriyaC/JQJGwnIcXdRg3S67WeKqMbLQXlBNtZf9Zrr45HIakYM6+zHfMljZN15Two/7S2c0vL1Vv03HycRbNcuHy/ZXyRBwMUj6c9DS92plY2bG7hxp6z1Qu35F7N3XU6AuvhOcObzhJe74BM5/scrIKB6WKFQvDvS0NUP1Fo8Mms5GleA+Y0/sfbQQN83eGWzrALHgJaeoat3Go0L7wlyu6iUbRXOpPiCxpWupjyrtg6/XreIxrSOYwIDAQAB
  sign-type: RSA2
  charset: UTF-8
  format: json
  gateway-url: https://openapi.alipay.com/gateway.do
  notify-url: http://42.194.245.66/single/payment/alipay/notify
  return-url: http://42.194.245.66/single/payment/alipay/return

# 日志配置
logging:
  level:
    com.platform: INFO
    org.springframework.web: INFO
    org.mybatis: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"

# 跨域配置
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:5173
    - http://127.0.0.1:3000
    - http://127.0.0.1:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Swagger配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  info:
    title: Information 知识付费平台 API
    description: 提供完整的知识付费平台功能接口
    version: 1.0.0
    contact:
      name: Platform Team
      email: support@information-platform.com