# Information 知识付费平台 - 本地开发环境配置
server:
  port: 8070
  servlet:
    context-path: /api

spring:
  # 数据源配置 - 本地MySQL
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: platform123456
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin123456

  # Redis配置 - 本地Redis (使用Redisson)
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://127.0.0.1:6379"
          password: "redis123456"
          database: 0
          connectionPoolSize: 64
          connectionMinimumIdleSize: 10
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500

  # 缓存配置
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m
      
  # 开发工具配置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false

# MyBatis Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开发环境显示SQL

# JWT配置
jwt:
  secret: InformationPlatformDevSecretKey2024ForDevelopment
  expiration: 604800000  # 7天，开发环境更长过期时间
  header: Authorization
  prefix: Bearer

# 文件上传配置
file:
  upload:
    path: /tmp/uploads/
    max-size: 50MB
    allowed-types: jpg,jpeg,png,gif,pdf,doc,docx,txt,md

# 支付配置 - 开发环境使用沙箱
alipay:
  appId: 2021005181654127
  privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCA9PyDQgZRftWPbIA2H0baLyrdZrxEMEGMv8akbvTW3kOQdmP9pP6wrw/8+4sD4cUz76qDB7mkpxn33CkFGaj7Xa+HOnICbwjqauLdEd1/wiwwNWeT3R6awOpjDsHo9QNRM628I0Zfj10OYy+h+yzVWefxyeOcw2yDAaYRr9hyBxuW3URDQ5AGe6X0IKZlQUDp7gXOpz/pTGCU+eGCbvSC+7OZnDtsEEcxmwjz4rhvtu15L82PCaCxKiUWd53hp0iiPkbrDMfU8BmcNvQOV7UvKyEZaPSDkhnH4p0AcmKN42SVgRx+kM6rfNEJgyJypeoAtiN+4YSEkvJXH4NmVzh9AgMBAAECggEAVzldsspty6GmgaQ59GGjYuCUdbyPiu+45qKwkXgbU1pzCLuLVnzLaGaAwfTCSpXi9QYepxIKlzwPbH8Vn8WDbsInf6gghVTlCunRGQaEc226xcDZlkHx+WqTHv1UW2WeIMZ7tM2HRAuMPbcI+N8TrBtrrzeHJPlp5BKxaTUvibAfFES0iW0mW+Z9ux58Wz7w5aeu5WMm9ekxWSnXKooLJsm9ZNGznOQRn1wM4+AvCKgYOneug8r+c6ROfGZ1qwFSPvRAC+GjHOxm+vczwxecP/lCFdYZJTVEl7J8DZQXMeqrbiKkDhQAMLyr0nO7jqWEG/czz/HxnR0NtLNXlW2jAQKBgQC9D8fBfaq2zF7VEQ5Mydp0/CiAvTp1B2yw1osA2pf4LMWrDtYGVIVpGjgqHPvhcFeqJ7Xdyyn0OXuWNeEzADY/Bduyd+LkiOJurzZcyJ38WQRsjf6Xz6Z8hHcQT4ga/L0KGeh7tRL6k45Tk9g+Pxe3Ycf0SJwAKuwnkm6KpAkuJQKBgQCunWxpDHWw11pYqZ6Sv2tYuRlZMalWQ8XdSNVB1lt1GfuccKEypsR9JEossEtnGACXhymWWJYP/hCVnlpYHVLuKnZEbctpnKF9DULZvg9KR6KmmNviTBHP6s/UlFyxJdw3UbP3aO5WibJbLvuGE3xZJNkeNwYS7pyE5vdnUEv1eQKBgDc5T8jl8yKYCa9E3x9w6p23NgF8xIGAnK/+yvWB5Ff6g/aWS8/nilyL6xHqC2zrSsAJ/2Z8vJF45O+YZ2JlUnMQO/8iY6ULktBv33o0o2kde1xWEaK4ZdIDQ2ABSylO38z+iljwKE4HIdCp48Uy2rOXHTfuqZqm7voUHLPkfEX9AoGARf44XItwCajpQC0NsUkloHTh4kzz0e5su9zcDv37vx7hKr5C/2i1zmvjh7JLJ1IJurOlSezMijCPOUo2cKegfHNs4NUZ+oWcfeH48AstWdsJKbqQOU/AvBUlpdKqrR+9/Da16vCWyP19DuvwSrg42grZNTFdL+2Rs/xZI4KeUBECgYAinTcSUxa6vO7m5qUD9xZm+utn/vB6GC3JCahcm38Vr3pzqlUImBTazDXD4agvh5xJqrmmzgDgZLmFYCoYdlCimDx9vAntISc5127o3w/VanlTli4RnnH7G2I9mylVeCC8g0JOp/Iigj0nZjS79+TbI/TGB03nQhQwlhr6Oh1xug==
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlCTj5jttp0gZAu+JyDGqGzUW9Ko4SNU80YLlStHJLY9WJ/kZhLZdKof6M0otKJbzByCCJJ3gFAr0X/Ej2Za17ZjAAwoivKPriyaC/JQJGwnIcXdRg3S67WeKqMbLQXlBNtZf9Zrr45HIakYM6+zHfMljZN15Two/7S2c0vL1Vv03HycRbNcuHy/ZXyRBwMUj6c9DS92plY2bG7hxp6z1Qu35F7N3XU6AuvhOcObzhJe74BM5/scrIKB6WKFQvDvS0NUP1Fo8Mms5GleA+Y0/sfbQQN83eGWzrALHgJaeoat3Go0L7wlyu6iUbRXOpPiCxpWupjyrtg6/XreIxrSOYwIDAQAB
  signType: RSA2
  charset: UTF-8
  format: json
  gatewayUrl: https://openapi.alipay.com/gateway.do  # 生产环境
  notifyUrl: http://42.194.245.66/single/payment/alipay/notify
  returnUrl: http://42.194.245.66/single/payment/alipay/return

wechatpay:
  appId: your-dev-wechat-app-id
  mchId: your-dev-wechat-mch-id
  apiKey: your-dev-wechat-api-key
  certPath: classpath:cert/dev_apiclient_cert.p12
  notifyUrl: http://localhost:8080/api/payment/wechat/notify

# 日志配置
logging:
  level:
    com.platform: DEBUG
    org.springframework.web: DEBUG
    org.mybatis: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 跨域配置 - 开发环境允许前端调用
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:5173
    - http://127.0.0.1:3000
    - http://127.0.0.1:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true


# Swagger配置 - 开发环境启用
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  info:
    title: Information 知识付费平台 API (开发环境)
    description: 提供完整的知识付费平台功能接口 - 开发测试版本
    version: 1.0.0-DEV
    contact:
      name: Development Team
      email: dev@information-platform.com

# 管理端点配置 - 开发环境开放更多端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# 异步配置
async:
  pool:
    core-size: 2
    max-size: 10
    queue-capacity: 100
    keep-alive: 60